apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-service-app
  labels:
    app: hotel-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app : hotel-service-app
  template:
    metadata:
      labels:
        app: hotel-service-app
    spec:
      containers:
        - name: hotel-service-app
          image: hdholakiya98/hotelservice-dockerfile:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082

---

kind: Service
apiVersion: v1
metadata:
  name:  hotel-service-svc
spec:
  selector:
    app:  hotel-service-app
  ports:
    - port:  80
      targetPort:  8082