apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server-app
  labels:
    app: config-server-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server-app
  template:
    metadata:
      labels:
        app: config-server-app
    spec:
      containers:
        - name: config-server-app
          image: hdholakiya98/configserver-dockerfile:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8085

---
apiVersion: v1
kind: Service
metadata:
  name: config-server-svc
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8085
      protocol: TCP
  selector:
    app: config-server-app